max_epochs = 50
learning_rate = 1e-3
accelerator = 'gpu'
weight_decay = 1e-4
strategy = 'auto'
num_workers = 7

[dataset]
stacks = 30
data_augmentation = '["random_node_dropout", "add_random_points", "random_translation", "random_rotation", "random_scaling", "time_stretching"]'
input_features = '["xyz"]'
posconv_features = '["xyz", "time", "velocity", "intensity"]'
posgraph_features = '["xyz"]'

[model]
fps_ratios = [0.3, 0.2]
radius = [0.4, 1.2]
